# Generated by Django 2.2 on 2024-06-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('pincode', models.IntegerField()),
                ('contactno', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(blank=True, max_length=50, null=True)),
                ('event_name', models.CharField(max_length=50)),
                ('advertisement_type', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('quality', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=1000)),
                ('sample_photo', models.FileField(upload_to='documents/')),
                ('order_date', models.DateField()),
                ('order_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('pay_date', models.DateField()),
                ('payment_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=50)),
                ('event_id', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('grand_total', models.CharField(max_length=50)),
                ('invoice_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewsPaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newspaper_name', models.CharField(max_length=50)),
                ('editor_name', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
                ('cost', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewspaperaddPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=50)),
                ('customer_id', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('payment_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewspaperaddRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='documents/')),
                ('request_date', models.DateField()),
                ('date_to_posted', models.DateField()),
                ('request_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('utype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=10)),
            ],
        ),
    ]
